/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lruCashe;

public class App {

	public static void main(String[] args) {
		LRUCacheClass lru = new LRUCacheClass();
    }
}
